name: 'python health checks'
description: 'A standard style check, lint, type check in the pipenv python environment'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install pipenv
      shell: bash
      run: |
        python -m pip install --upgrade pipenv wheel

    - id: cache-pipenv
      uses: actions/cache@v3
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        pipenv sync --dev

    - name: Check format is compliant
      shell: bash
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: pipenv run style-check

    - name: Lint
      shell: bash
      run: pipenv run lint

    - name: Type checking
      shell: bash
      run: pipenv run type-check
