# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 'python health checks'

on:
  workflow_call:

permissions:
  contents: read

jobs:
  # This job does the generic python setup
  check_python_code_health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          pipenv sync --dev

      - name: Check format is compliant
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: pipenv run style-check

      - name: Lint
        run: pipenv run lint

      - name: Type checking
        run: pipenv run type-check

      - name: Unit testing
        run: pipenv run test
